image: python:2.7

pipelines:
  default:
    - step:
        caches:
          - buildout
        script:
          - pip install zc.buildout
          - buildout -n buildout:eggs-directory=../eggs
          - bin/py.test
definitions:
  caches:
    buildout: ../eggs
