# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: python:2.7

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - pip install setuptools==34.3.0 zc.buildout
          - buildout -n buildout:eggs-directory=../eggs
          - bin/py.test